//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfonetPOS.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InfonetPOS.Core.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Paid.
        /// </summary>
        public static string AmountPaid {
            get {
                return ResourceManager.GetString("AmountPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Payable.
        /// </summary>
        public static string AmountPayable {
            get {
                return ResourceManager.GetString("AmountPayable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount To Return.
        /// </summary>
        public static string AmountToReturn {
            get {
                return ResourceManager.GetString("AmountToReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorize for pump test.
        /// </summary>
        public static string AuthorizeForPumpTest {
            get {
                return ResourceManager.GetString("AuthorizeForPumpTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t Hold Basket.Try again after sometimes..
        /// </summary>
        public static string BasketHoldError {
            get {
                return ResourceManager.GetString("BasketHoldError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate Amount.
        /// </summary>
        public static string CalculateAmount {
            get {
                return ResourceManager.GetString("CalculateAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basket hold can&apos;t be cancelled.Try again after sometimes..
        /// </summary>
        public static string CancelHoldBasketError {
            get {
                return ResourceManager.GetString("CancelHoldBasketError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t  Authorize for pump test.Please try again..
        /// </summary>
        public static string CantAuthorizeForPumpTest {
            get {
                return ResourceManager.GetString("CantAuthorizeForPumpTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cant Authorize pump for postpay. Try Again after somethimes..
        /// </summary>
        public static string CantAuthorizePostPay {
            get {
                return ResourceManager.GetString("CantAuthorizePostPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAN NOT AUTHORIZE PUMP.
        /// </summary>
        public static string CantAuthorizePump {
            get {
                return ResourceManager.GetString("CantAuthorizePump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in the middle of a transaction. Please complete or cancel the transaction before you close the application..
        /// </summary>
        public static string CantCloseApp {
            get {
                return ResourceManager.GetString("CantCloseApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t set price. Try again after sometimes..
        /// </summary>
        public static string CantSetPrice {
            get {
                return ResourceManager.GetString("CantSetPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t Start all pump.Try Again after sometimes..
        /// </summary>
        public static string CantStartAllPump {
            get {
                return ResourceManager.GetString("CantStartAllPump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t start pump.Please Try Again After sometimes..
        /// </summary>
        public static string CantStartPump {
            get {
                return ResourceManager.GetString("CantStartPump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t Stop all pump.Try again after sometimes..
        /// </summary>
        public static string CantStopAllPump {
            get {
                return ResourceManager.GetString("CantStopAllPump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t stop pump.Please Try Again After sometimes..
        /// </summary>
        public static string CantStopPump {
            get {
                return ResourceManager.GetString("CantStopPump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t Switch prepay.Try again after sometimes..
        /// </summary>
        public static string CantSwitchPrepay {
            get {
                return ResourceManager.GetString("CantSwitchPrepay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to close the till?.
        /// </summary>
        public static string CloseTill {
            get {
                return ResourceManager.GetString("CloseTill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to Back office/FCS lost. Please check your network/WIFI connection. Do you want to try again?.
        /// </summary>
        public static string ConnectionLoseWhileLogin {
            get {
                return ResourceManager.GetString("ConnectionLoseWhileLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to Back office/FCS lost, please ensure your network/WIFI connection is ok and try again..
        /// </summary>
        public static string ConnectionLoseWhileLogout {
            get {
                return ResourceManager.GetString("ConnectionLoseWhileLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLEASE CONTACT YOUR DEALER.
        /// </summary>
        public static string ContactDealer {
            get {
                return ResourceManager.GetString("ContactDealer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converted Amount.
        /// </summary>
        public static string ConvertedAmount {
            get {
                return ResourceManager.GetString("ConvertedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Price.
        /// </summary>
        public static string CurrentPrice {
            get {
                return ResourceManager.GetString("CurrentPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Sales .
        /// </summary>
        public static string CurrentSales {
            get {
                return ResourceManager.GetString("CurrentSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTime.
        /// </summary>
        public static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive Off.
        /// </summary>
        public static string DriveOff {
            get {
                return ResourceManager.GetString("DriveOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete As Drive Off?.
        /// </summary>
        public static string DriveOffMessage {
            get {
                return ResourceManager.GetString("DriveOffMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter password to login..
        /// </summary>
        public static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EOD Report.
        /// </summary>
        public static string EOD {
            get {
                return ResourceManager.GetString("EOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed EOD Report.
        /// </summary>
        public static string EODDetail {
            get {
                return ResourceManager.GetString("EODDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Rate.
        /// </summary>
        public static string ExchangeRate {
            get {
                return ResourceManager.GetString("ExchangeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Grade.
        /// </summary>
        public static string FuelGrade {
            get {
                return ResourceManager.GetString("FuelGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Price Change.
        /// </summary>
        public static string FuelPriceChange {
            get {
                return ResourceManager.GetString("FuelPriceChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Server Not Available.
        /// </summary>
        public static string FuelServerNotAvailable {
            get {
                return ResourceManager.GetString("FuelServerNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas Price Change Report.
        /// </summary>
        public static string GasPriceChange {
            get {
                return ResourceManager.GetString("GasPriceChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GO TO PUMP {0} AND LIFT NOZZLE TO BEGIN FUELING.
        /// </summary>
        public static string GotoToPump {
            get {
                return ResourceManager.GetString("GotoToPump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas Sales Hourly Report.
        /// </summary>
        public static string HourlyGasSales {
            get {
                return ResourceManager.GetString("HourlyGasSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        public static string Invoice {
            get {
                return ResourceManager.GetString("Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGOUT.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Price.
        /// </summary>
        public static string NewPrice {
            get {
                return ResourceManager.GetString("NewPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Day.
        /// </summary>
        public static string NextDay {
            get {
                return ResourceManager.GetString("NextDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOU DON’T HAVE PERMISSION TO LOGIN TO POS.
        /// </summary>
        public static string NoPermissionToLogIn {
            get {
                return ResourceManager.GetString("NoPermissionToLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        public static string Paid {
            get {
                return ResourceManager.GetString("Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARTIALLY PUMPED.
        /// </summary>
        public static string PartialPumping {
            get {
                return ResourceManager.GetString("PartialPumping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAYMENT APPROVED.
        /// </summary>
        public static string PaymentApproved {
            get {
                return ResourceManager.GetString("PaymentApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method.
        /// </summary>
        public static string PaymentMethod {
            get {
                return ResourceManager.GetString("PaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAYMENT NOT APPROVED.
        /// </summary>
        public static string PaymentNotApproved {
            get {
                return ResourceManager.GetString("PaymentNotApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Solution Not Available.
        /// </summary>
        public static string PaymentSolutionNotAvailable {
            get {
                return ResourceManager.GetString("PaymentSolutionNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepay.
        /// </summary>
        public static string Prepay {
            get {
                return ResourceManager.GetString("Prepay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepay cancel hold remove error occurred.Try again after sometimes..
        /// </summary>
        public static string PrepayCancelHoldRemoveError {
            get {
                return ResourceManager.GetString("PrepayCancelHoldRemoveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepay for pump: {0}.
        /// </summary>
        public static string PrepayForPump {
            get {
                return ResourceManager.GetString("PrepayForPump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrepayHold Error Occurred.Try Again after sometimes..
        /// </summary>
        public static string PrepayHoldError {
            get {
                return ResourceManager.GetString("PrepayHoldError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepay Hold Remove error occurred. Try again..
        /// </summary>
        public static string PrepayHoldRemoveError {
            get {
                return ResourceManager.GetString("PrepayHoldRemoveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PREPAY HAS BEEN REMOVED.
        /// </summary>
        public static string PrepayRemoved {
            get {
                return ResourceManager.GetString("PrepayRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Day.
        /// </summary>
        public static string PreviousDay {
            get {
                return ResourceManager.GetString("PreviousDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing Receipt....
        /// </summary>
        public static string PrintingReceipt {
            get {
                return ResourceManager.GetString("PrintingReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing Report.
        /// </summary>
        public static string PrintingReport {
            get {
                return ResourceManager.GetString("PrintingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Report.
        /// </summary>
        public static string PrintReport {
            get {
                return ResourceManager.GetString("PrintReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROCESSING…..
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pump.
        /// </summary>
        public static string Pump {
            get {
                return ResourceManager.GetString("Pump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pump Test.
        /// </summary>
        public static string PumpTest {
            get {
                return ResourceManager.GetString("PumpTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete As Pump Test?.
        /// </summary>
        public static string PumpTestMessage {
            get {
                return ResourceManager.GetString("PumpTestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipts For {0}.
        /// </summary>
        public static string ReceiptsFor {
            get {
                return ResourceManager.GetString("ReceiptsFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt Type.
        /// </summary>
        public static string ReceiptType {
            get {
                return ResourceManager.GetString("ReceiptType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REFUND.
        /// </summary>
        public static string Refund {
            get {
                return ResourceManager.GetString("Refund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund Approved.
        /// </summary>
        public static string RefundApproved {
            get {
                return ResourceManager.GetString("RefundApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund Method.
        /// </summary>
        public static string RefundMethod {
            get {
                return ResourceManager.GetString("RefundMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund Not Approved.
        /// </summary>
        public static string RefundNotApproved {
            get {
                return ResourceManager.GetString("RefundNotApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund Not approved.Please contact with cashier..
        /// </summary>
        public static string RefundNotApprovedForPrepayRefund {
            get {
                return ResourceManager.GetString("RefundNotApprovedForPrepayRefund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reprint Receipt.
        /// </summary>
        public static string ReprintReceipt {
            get {
                return ResourceManager.GetString("ReprintReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Payment Method.
        /// </summary>
        public static string SelectPaymentMethod {
            get {
                return ResourceManager.GetString("SelectPaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Refund Method.
        /// </summary>
        public static string SelectRefundMethod {
            get {
                return ResourceManager.GetString("SelectRefundMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        public static string Set {
            get {
                return ResourceManager.GetString("Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET AMOUNT.
        /// </summary>
        public static string SetAmount {
            get {
                return ResourceManager.GetString("SetAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        public static string Shift {
            get {
                return ResourceManager.GetString("Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Report.
        /// </summary>
        public static string ShowReport {
            get {
                return ResourceManager.GetString("ShowReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start All Pumps.
        /// </summary>
        public static string StartAll {
            get {
                return ResourceManager.GetString("StartAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop All Pumps.
        /// </summary>
        public static string StopAll {
            get {
                return ResourceManager.GetString("StopAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Till.
        /// </summary>
        public static string Till {
            get {
                return ResourceManager.GetString("Till", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TO PROCESS PAYMENT.
        /// </summary>
        public static string ToProcessPayment {
            get {
                return ResourceManager.GetString("ToProcessPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLEASE USE PAYMENT TERMINAL.
        /// </summary>
        public static string UsePaymentTerminal {
            get {
                return ResourceManager.GetString("UsePaymentTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to authorize for pump test?.
        /// </summary>
        public static string WantToAuthorizeForPumpTest {
            get {
                return ResourceManager.GetString("WantToAuthorizeForPumpTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do You Want To Start All Pumps?.
        /// </summary>
        public static string WantToStartPumps {
            get {
                return ResourceManager.GetString("WantToStartPumps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do You Want TO Stop All Pumps?.
        /// </summary>
        public static string WantToStopPumps {
            get {
                return ResourceManager.GetString("WantToStopPumps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is incorrect..
        /// </summary>
        public static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YES.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
